name: MinigamesLib
main: com.comze_instancelabs.minigamesapi.MinigamesAPI
version: 1.4.0
author: InstanceLabs
softdepend: [Vault]
commands:
   mapi:
      description: Main command
      usage: /mapi [action]
