name: MinigamesLib
main: com.comze_instancelabs.minigamesapi.MinigamesAPI
version: 1.9.4
author: InstanceLabs
softdepend: [Vault]
commands:
   mapi:
      description: Main command
      usage: /mapi [action]
   party:
      description: Main Party command
      usage: /party [action]
